### PR TITLE
Change compile to implementation in build.gradle

### PR DESCRIPTION
**Pull request by SIMULATAN**
Reason: [compile is deprecated since 3.4](https://docs.gradle.org/current/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations)

### CODE REVIEW

**Comment by SIMULATAN** [comment]
@Spark61

**Comment by Spark61** [comment]
@SIMULATAN

**Comment by SIMULATAN** [comment]
> @SIMULATAN 

Merge Mal bitte

**Comment by SIMULATAN** [comment]
Boah aktiv hier

**Comment by SIMULATAN** [comment]
@Spark61 are you dead?

**Comment by Spark61** [comment]
> @Spark61 are you dead?

Yeah

**Pull request merged**
